language: python
sudo: false

matrix:
  include:
  - python: 2.7
    env: NOX_SESSION="lint"
  - python: 2.7
    env: NOX_SESSION="tests(interpreter='python2.7')"
  - python: 3.4
    env: NOX_SESSION="tests(interpreter='python3.4')"
  - python: 3.5
    env: NOX_SESSION="tests(interpreter='python3.5')"
  - python: 2.7
    env: NOX_SESSION="tests_gaesdk"

install:
- pip install nox-automation==0.19.1 codecov

script:
- nox -s "$NOX_SESSION"

after_success:
- if [[ "${NOX_SESSION}" == "tests_gaesdk" ]]; then codecov; fi
